wip
Change-Id: I3c204352e5d822c5bf7fad0785c1a1bb23262485

diff --git a/doit b/doit
--- a/doit
+++ b/doit
@@ -7,6 +7,8 @@ set -e
 #old=/scratch/sglass/coral/chroot/build/coral/firmware/image-coral.dev.bin
 old=/scratch/sglass/coral/chroot/build/coral/firmware/image-coral.bin
 
+devkeys_dir=cros/data/devkeys
+
 new=cb.bin
 ub=/tmp/b/chromeos_coral
 name=fallback/payload
@@ -92,10 +94,72 @@ do_part() {
 	fi
 }
 
+do_cbfstool() {
+	local output
+	output=$(cbfstool "$@" 2>&1)
+	if [ $? != 0 ]; then
+		die "Failed cbfstool invocation: cbfstool $@\n${output}"
+	fi
+	printf "${output}"
+}
+
+sign_region() {
+	local fw_image=$1
+	local keydir=$2
+	local slot=$3
+
+	local tmpfile=`mktemp`
+	local cbfs=FW_MAIN_${slot}
+	local vblock=VBLOCK_${slot}
+
+	do_cbfstool ${fw_image} read -r ${cbfs} -f ${tmpfile}
+	local size=$(do_cbfstool ${fw_image} print -k -r ${cbfs} | \
+		tail -1 | \
+		sed "/(empty).*null/ s,^(empty)[[:space:]]\(0x[0-9a-f]*\)\tnull\t.*$,\1,")
+	size=$(printf "%d" ${size})
+
+	# If the last entry is called "(empty)" and of type "null", remove it from
+	# the section so it isn't part of the signed data, to improve boot speed
+	# if (as often happens) there's a large unused suffix.
+	if [ -n "${size}" ] && [ ${size} -gt 0 ]; then
+		head -c ${size} ${tmpfile} > ${tmpfile}.2
+		mv ${tmpfile}.2 ${tmpfile}
+		# Use 255 (aka 0xff) as the filler, this greatly reduces
+		# memory areas which need to be programmed for spi flash
+		# chips, because the erase value is 0xff.
+		do_cbfstool ${fw_image} write --force -u -i 255 \
+			-r ${cbfs} -f ${tmpfile}
+	fi
+
+	futility vbutil_firmware \
+		--vblock ${tmpfile}.out \
+		--keyblock ${keydir}/firmware.keyblock \
+		--signprivate ${keydir}/firmware_data_key.vbprivk \
+		--version 1 \
+		--fv ${tmpfile} \
+		--kernelkey ${keydir}/kernel_subkey.vbpubk \
+		--flags 0
+
+	do_cbfstool ${fw_image} write -u -i 255 -r ${vblock} -f ${tmpfile}.out
+
+	rm -f ${tmpfile} ${tmpfile}.out
+}
+
+sign_image() {
+	local fw_image=$1
+	local keydir=$2
+
+	sign_region "${fw_image}" "${keydir}" A
+	sign_region "${fw_image}" "${keydir}" B
+}
+
 # Do read/write and recovery
 do_part "-r FW_MAIN_A"
 do_part "-r FW_MAIN_B"
 do_part
+
+sign_image $new "${devkeys_dir}"
+
 
 # Put valid MRC-cache data in there for a faster boot
 cbfstool $new write -r RW_MRC_CACHE -f RW_MRC_CACHE
